### ISSUE TITLE
Saving robot player code

### ISSUE THREAD

**Issue by dybber** [DatalogiForAlle/Markedsspillet#209]
Would users request the ability to save their projects? Would robot players then require players to have their own login?

**Comment by KristianMSchmidt** [comment]
I don't think this is required. We want it to be easy for players to join and we have previously decided that login is only for teachers. 

In the current implementation, the player code is saved locally in the browser's localStorage when you press the "auto-play" button. Instead of the database + login solution, a simple solution would be to add a "Don't forget to save your code"-warning on the player page after a robot-game has ended + perhaps a "download your code"-button
